version: '3.9'

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        command: node build/index.js
        restart: on-failure
        depends_on:
            -   webhook

    webhook:
        image: "almir/webhook"
        command:
            - -verbose
            - -hooks=/etc/webhook/hooks.json
            - -hotreload
        container_name: webhook
        ports:
            - "9000:9000"
        volumes:
            - /home/ec2-user/webhooks:/etc/webhook
            - /home/ec2-user/webhooks:/home/ec2-user/webhooks
            - /home/ec2-user/projects/learning-docker:/home/ec2-user/projects/learning-docker

    nginxmanager:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: on-failure
        ports:
            - '80:80' # Public HTTP Port
            - '443:443' # Public HTTPS Port
        volumes:
            - ./data:/data
            - ./letsencrypt:/etc/letsencrypt
            - ./conf.d:/data/nginx/custom/
        depends_on:
            - webhook
