version: '3.9'

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        volumes:
            - ./src/:/home/node/app/src
            - ./nodemon.json:/home/node/app/nodemon.json
        command: npm run dev
    nginxmanager:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: on-failure
        ports:
            - '80:80' # Public HTTP Port
            - '443:443' # Public HTTPS Port
        volumes:
            - ./data:/data
            - ./letsencrypt:/etc/letsencrypt
            - ./conf.d:/data/nginx/custom/
        extra_hosts:
            - "host.docker.internal:host-gateway"
