version: '3.9'

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        command: node build/index.js
    nginxmanager:
        image: 'jc21/nginx-proxy-manager:latest'
        restart: unless-stopped
        ports:
            # These ports are in format <host-port>:<container-port>
            - '80:80' # Public HTTP Port
            - '443:443' # Public HTTPS Port
        volumes:
            - ./data:/data
            - ./letsencrypt:/etc/letsencrypt
            - ./conf.d:/data/nginx/custom/
