version: '3.9'

services:
    api: 
        build: 
            context: .
            dockerfile: Dockerfile
            target: production
        command: node build/index.js
    nginx: 
        image: nginx:latest
        volumes:
            - ./conf.d:/etc/nginx/conf.d
        depends_on:
            - api
        expose: 
            - '3000'
        ports:
            - '3000:3000'