version: '3.9'

services:
    api: 
        build: 
            context: .
            dockerfile: Dockerfile
            target: base
        volumes:
            - ./src/:/home/node/app/src
            - ./nodemon.json:/home/node/app/nodemon.json
        command: npm run dev
    nginx: 
        image: nginx:latest
        volumes:
            - ./conf.d:/etc/nginx/conf.d
        depends_on:
            - api
        expose: 
            - '3000'
        ports:
            - '3000:3000'